spring.application.name=bdMetro

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/metroBD
spring.datasource.username=postgres
spring.datasource.password=Tanque.123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server
server.port=8080

# Recursos est\u00E1ticos (uploads)
spring.web.resources.static-locations=classpath:/static/,file:./uploads/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.mvc.static-path-pattern=/uploads/**

# Base URL (para uploads)
app.base-url=http://localhost:8080
spring.jackson.serialization.fail-on-empty-beans=false

#spring.profiles.active=${SPRING_PROFILES_ACTIVE:default}

# Mercado Pago
mercadopago.enabled=true
mercadopago.base-url=https://api.mercadopago.com
mercadopago.access-token=APP_USR-5320915888941206-032411-29b1097573595d974fe48103808aa867-2392507839
mercadopago.webhook-secret=0ecf8579652187e0555e74b51497bc3120e9967a28d8c52a87a386e1505ee05e
mercadopago.success-url=http://localhost:4200/payment-result
mercadopago.failure-url=http://localhost:4200/payment-result
mercadopago.pending-url=http://localhost:4200/payment-result

# Membership payments catalog
payments.membership.notification-path=/api/payments/memberships/mercadopago/webhook
payments.membership.default-callback-url=http://localhost:4200/payment-result
payments.membership.base-plans-usd.3=5
payments.membership.base-plans-usd.6=8
payments.membership.catalog.AR.enabled=true
payments.membership.catalog.AR.display-name=Argentina
payments.membership.catalog.AR.currency=ARS
payments.membership.catalog.AR.document-label=DNI o CUIT
payments.membership.catalog.UY.enabled=true
payments.membership.catalog.UY.display-name=Uruguay
payments.membership.catalog.UY.currency=UYU
payments.membership.catalog.UY.document-label=CI o RUT
payments.membership.catalog.CO.enabled=true
payments.membership.catalog.CO.display-name=Colombia
payments.membership.catalog.CO.currency=COP
payments.membership.catalog.CO.document-label=CC o NIT

# PayPal
paypal.enabled=true
paypal.client-id=AdANtXSpa5_q1fq0q3Itc-1HXJNnR0QWjSTqpsy3DhWWTHPG5ealjix9neVdzbUAC3B0wxtBFID3fSVK
paypal.client-secret=REEMPLAZA_CON_TU_SECRET_REAL
paypal.base-url=https://api-m.sandbox.paypal.com
paypal.success-url=http://localhost:4200/payment-result
paypal.cancel-url=http://localhost:4200/payment-result

# FX
fx.base-url=https://open.er-api.com/v6/latest
fx.base-currency=USD
fx.cache-minutes=15
fx.fallback-rates.ARS=1080
fx.fallback-rates.UYU=42
fx.fallback-rates.COP=3950
